### ISSUE TITLE
Relicense Font under a less restrictive license.

### ISSUE THREAD

**Issue by Zanthas** [Zanthas/tewi-font#1]
I'd like permission from @lucy and @tobbez to relicense my fork under the MIT/X11 License. The original tewi can of course stay GPL. This relicense will only apply to my fork.

**Comment by tobbez** [comment]
I don't mind.

**Comment by Zanthas** [comment]
Seems Tewi was relicensed to MIT/X11
[Link](https://github.com/lucy/tewi-font/commit/75b2c79df6d28f2bd53a2c826ec0ee41bd673eed)
I'll close this now and keep this fork GPL'd

**Comment by lucy** [comment]
: )
